[package]
name = "ellip-error-report"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"
description = "Generate error report for Ellip crate"

[dependencies]
ellip = { version = "0.3.4", path = "../.." }
csv = "1.3.1"
tabled = "0.18.0"
num-traits = "0.2.19"
