/*
 * Ellip is licensed under The 3-Clause BSD, see LICENSE.
 * Copyright 2025 Sira Pornsiriprasert <code@psira.me>
 * This code is translated from Boost Math.
 */

// Original header from Boost Math
//  Copyright (c) 2006 Xiaogang Zhang, 2015 John Maddock
//  Copyright (c) 2024 Matt Borland
//  Use, modification and distribution are subject to the
//  Boost Software License, Version 1.0. (See accompanying file
//  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
//  History:
//  XZ wrote the original of this file as part of the Google
//  Summer of Code 2006.  JM modified it to fit into the
//  Boost.Math conceptual framework better, and to handle
//  types longer than 80-bit reals.
//  Updated 2015 to use Carlson's latest methods.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

use std::{f64::consts::PI, mem::swap};

use crate::elliprc;

/// Compute [symmetric elliptic integral of the first kind](https://dlmf.nist.gov/19.16.E1).
/// ```text
///                     ∞                              
///                 1  ⌠             dt              
/// RF(x, y, z)  =  ─  ⎮ ───────────────────────────
///                 2  ⎮   ________________________
///                    ⌡ ╲╱(t + x) (t + y) (t + z)
///                   0                              
/// where x ≥ 0, y ≥ 0, z ≥ 0, and at most one can be zero.
/// ```
///
pub fn elliprf(x: f64, y: f64, z: f64) -> Result<f64, &'static str> {
    if x.min(y).min(z) < 0.0 || (y + z).min(x + y).min(x + z) < 0.0 {
        return Err("elliprf: x, y, and z must be non-negative, and at most one can be zero.");
    }

    // Special cases from http://dlmf.nist.gov/19.20#i
    if x == y {
        if x == z {
            // RF(x,x,x)
            return Ok(1.0 / x.sqrt());
        }

        if z == 0.0 {
            // RF(x,x,0)
            // RF(0,y,y)
            return Ok(PI / (2.0 * x.sqrt()));
        }

        // RF(x,x,z)
        // RF(x,y,y)
        return elliprc(z, x);
    }

    if x == z {
        if y == 0.0 {
            // RF(x,0,x)
            // RF(0,y,y)
            return Ok(PI / (2.0 * x.sqrt()));
        }

        // RF(x,y,x)
        // RF(x,y,y)
        return elliprc(y, x);
    }

    if y == z {
        if x == 0.0 {
            // RF(0,y,y)
            return Ok(PI / (2.0 * y.sqrt()));
        }

        // RF(x,y,y)
        return elliprc(x, y);
    }

    let mut xn = x;
    let mut yn = y;
    let mut zn = z;

    if xn == 0.0 {
        swap(&mut xn, &mut zn);
    } else if yn == 0.0 {
        swap(&mut yn, &mut zn);
    }

    if zn == 0.0 {
        let mut xn = xn.sqrt();
        let mut yn = yn.sqrt();

        while (xn - yn).abs() >= 2.7 * f64::EPSILON * xn.abs() {
            let t = (xn * yn).sqrt();
            xn = (xn + yn) / 2.0;
            yn = t;
        }
        return Ok(PI / (xn + yn));
    }

    let mut an = (xn + yn + zn) / 3.0;
    let a0 = an;
    let mut q = (3.0 * f64::EPSILON).powf(-1.0 / 8.0)
        * an.abs()
            .max((an - xn).abs())
            .max((an - yn).abs())
            .max((an - zn).abs());
    let mut fn_val = 1.0;
    let mut it = 0;
    for _ in 0..N_MAX_ITERATIONS {
        let root_x = xn.sqrt();
        let root_y = yn.sqrt();
        let root_z = zn.sqrt();

        let lambda = root_x * root_y + root_x * root_z + root_y * root_z;

        an = (an + lambda) / 4.0;
        xn = (xn + lambda) / 4.0;
        yn = (yn + lambda) / 4.0;
        zn = (zn + lambda) / 4.0;

        q /= 4.0;
        fn_val *= 4.0;

        if q < an.abs() {
            break;
        }
        it += 1;
    }
    if it == N_MAX_ITERATIONS {
        return Err("elliprf: Fail to converge.");
    }

    let x = (a0 - x) / (an * fn_val);
    let y = (a0 - y) / (an * fn_val);
    let z = -x - y;

    let e2 = x * y - z * z;
    let e3 = x * y * z;

    Ok((1.0
        + e3 * (1.0 / 14.0 + 3.0 * e3 / 104.0)
        + e2 * (-1.0 / 10.0 + e2 / 24.0 - (3.0 * e3) / 44.0 - 5.0 * e2 * e2 / 208.0
            + e2 * e3 / 16.0))
        / an.sqrt())
}

const N_MAX_ITERATIONS: usize = 11;

#[cfg(test)]
mod test {
    use itertools::Itertools;

    use super::*;
    use crate::{assert_close, compare_test_data};

    fn __elliprf(inp: &Vec<&f64>) -> f64 {
        elliprf(*inp[0], *inp[1], *inp[2]).unwrap()
    }

    fn _elliprf(inp: &[f64]) -> f64 {
        let res = elliprf(inp[0], inp[1], inp[2]).unwrap();
        inp.iter().permutations(inp.len()).skip(1).for_each(|perm| {
            assert_close!(res, __elliprf(&perm), 6.5e-16);
        });
        res
    }

    #[test]
    fn test_elliprf() {
        compare_test_data!("./tests/data/boost/ellint_rf_data.txt", _elliprf, 4.5e-16);
    }

    #[test]
    fn test_elliprf_xxx() {
        compare_test_data!("./tests/data/boost/ellint_rf_xxx.txt", _elliprf, 2.3e-16);
    }

    #[test]
    fn test_elliprf_xy0() {
        compare_test_data!("./tests/data/boost/ellint_rf_xy0.txt", _elliprf, 4.2e-16);
    }

    #[test]
    fn test_elliprf_xyy() {
        compare_test_data!("./tests/data/boost/ellint_rf_xyy.txt", _elliprf, 5.3e-16);
    }
}
