name: Plot Graphs for Ellip

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  plot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin: [cel, cel1, cel2, el1, el2, el3, ellipd, ellipdinc, ellipe, ellipeinc, ellipf, ellipk, elliprc, elliprd, elliprf, elliprg, elliprj]
    steps:
      - uses: actions/checkout@v4
      - name: Plot ${{ matrix.bin }} with retries
        run: |
          set -e
          ATTEMPTS=0
          MAX_ATTEMPTS=3
          until [ $ATTEMPTS -ge $MAX_ATTEMPTS ]
          do
            if timeout 180s cargo run --bin ${{ matrix.bin }} --features save-to-bin; then
              echo "Plot succeeded"
              break
            else
              ATTEMPTS=$((ATTEMPTS+1))
              echo "Attempt $ATTEMPTS failed. Retrying..."
              if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
                echo "All $MAX_ATTEMPTS attempts failed. Exiting."
                exit 1
              fi
            fi
          done
        working-directory: examples/plot-graph
      - name: Move plots to bin-specific directory
        run: |
          mkdir -p figures/${{ matrix.bin }}
          mv figures/bin/* figures/${{ matrix.bin }}/ || true
        working-directory: examples/plot-graph
      - name: Save plots
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bin }}-plots
          path: figures/${{ matrix.bin }}/*

  commit:
    runs-on: ubuntu-latest
    needs: plot
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Download all plots
        uses: actions/download-artifact@v4
        with:
          path: all_figures/
          merge-multiple: true
      - name: Move all plots to figures
        run: |
          mkdir -p figures
          find all_figures -type f -exec mv {} figures/ \;
      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add figures/
          git diff --cached --quiet || (git commit -m "DOC: CI Plot 2D Graphs")
          git pull --rebase origin main
          git push