name: Plot Graphs for Ellip

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  plot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin: [cel, cel1, cel2, el1, el2, el3, ellipd, ellipdinc, ellipe, ellipeinc, ellipf, ellipk, ellippi, elliprc, elliprd, elliprf, elliprg, elliprj]
    steps:
      - uses: actions/checkout@v4
      - name: Plot ${{ matrix.bin }}
        run: |
          cd examples/plot-graph
          cargo run --bin ${{ matrix.bin }}
      - uses: actions/checkout@v4
      - name: Save plots
        uses: actions/upload-artifact@v4
        with:
          path: figures/*

  commit:
    runs-on: ubuntu-latest
    needs: plot
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Download all plots
        uses: actions/download-artifact@v4
        with:
          path: figures/
      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git diff --cached --quiet || (git commit -m "DOC: CI Plot 2D Graphs")
          git pull --rebase origin main
          git push