name: Ellip Report

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:  
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate Error Report
      run: cargo run --example generate_error_report
    - name: Commit & Push
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git diff --cached --quiet || git commit -m "DOC: CI Generated Error Report"
        git pull --rebase origin main
        git push
